export  const ActionTypes={
    SET_PRODUCTS: "SET_PRODUCTS",
    FAV_PRODUCTS: "FAV_PRODUCTS",
    CART_PRODUCTS: "CART_PRODUCTS",
    ADD_CART_PRODUCTS: "ADD_CART_PRODUCTS",
    REMOVE_CART_PRODUCTS: "REMOVE_CART_PRODUCTS",
    ADD_NEW_PRODUCT: "ADD_NEW_PRODUCT",
    ADD_NEW_USER:"ADD_NEW_USER",
    ADD_LOGIN_USER:"ADD_LOGIN_USER"

};